type: chart
builds:
  - image: samsung_cnct/cma-operator
    context: cma-operator
    chart: cma-operator
    value: image.repo
    dockerContext: .
deployments:
  - chart: cma-operator
    timeout: 600
    retries: 2
    release: cma-operator
    test:
      values:
        - key: bundles.metrics
          value: "false"
        - key: bundles.nginxk8smon
          value: "false"
        - key: bundles.nodelabelbot5000
          value: "false"
prod:
  doDeploy: none
