---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ template "chartname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      serviceAccountName: {{ .Release.Name }}-serviceaccount
      containers:
      - name: {{ template "name" . }}
        image: "{{.Values.image.repo}}"
        imagePullPolicy: "Always"
        env:
        {{- if .Values.cma.enabled }}
        - name: CMAOPERATOR_CMA_ENDPOINT
          value: "{{.Values.cma.endpoint }}"
        - name: CMAOPERATOR_CMA_API_PROXY
          value: "{{.Values.cma.apiProxyEndpoint }}"
        - name: CMAOPERATOR_CMA_API_PROXY_TLS
          value: "{{.Values.cma.apiProxyTls }}"
        - name: CMAOPERATOR_CMA_INSECURE
          value: "{{.Values.cma.insecure }}"
        {{- end }}
        - name: CMAOPERATOR_KUBERNETES_NAMESPACE
          value: "{{ .Release.Namespace}}"
